# Generated by Django 5.0.7 on 2024-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='/static/images/avatar/avatar.jpg', null=True, upload_to='profile_images', verbose_name='تصویر پروفایل'),
        ),
    ]
