# Generated by Django 5.0.7 on 2024-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profile_images/avatar.jpg', null=True, upload_to='profile_images', verbose_name='تصویر پروفایل'),
        ),
    ]
