# Generated by Django 5.0.7 on 2024-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_products_off_endtime'),
        ('user_module', '0006_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_products',
            field=models.ManyToManyField(null=True, to='product_module.products', verbose_name='علاقه مندی ها'),
        ),
    ]
