# Generated by Django 5.0.7 on 2024-07-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_user_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist_products',
        ),
    ]
