# Generated by Django 5.0.7 on 2024-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_with_off',
            field=models.IntegerField(null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
