# Generated by Django 4.2.6 on 2024-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون از فونت اوسام'),
        ),
    ]
