# Generated by Django 5.0.7 on 2024-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='product_imgs', verbose_name='تصویر محصول'),
        ),
    ]
