# Generated by Django 5.0.7 on 2024-07-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_products_off_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='off_time',
            field=models.TimeField(null=True, verbose_name='زمان تخفیف'),
        ),
    ]
