# Generated by Django 5.0.7 on 2024-07-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_products_off_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='off_time',
        ),
    ]
