# Generated by Django 5.0.7 on 2024-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_products_off_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='off_endtime',
            field=models.DateTimeField(null=True, verbose_name='زمان اتمام تخفیف'),
        ),
    ]
