# Generated by Django 5.0.7 on 2024-07-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_products_off_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='off_endtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام تخفیف'),
        ),
    ]
