# Generated by Django 5.0.7 on 2024-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_products_off_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد محصول موجود'),
        ),
        migrations.AddField(
            model_name='products',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید محصول'),
        ),
    ]
