# Generated by Django 5.0.7 on 2024-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistproducts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است/نیست'),
        ),
    ]
