# Generated by Django 5.0.7 on 2024-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel_module', '0002_wishlistproducts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproducts',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال است/نیست'),
        ),
    ]
