# Generated by Django 5.0.7 on 2024-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel_module', '0003_alter_wishlistproducts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproducts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است/نیست'),
        ),
    ]
