# Generated by Django 5.0.7 on 2024-08-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_products_off_endtime'),
        ('userpanel_module', '0004_alter_wishlistproducts_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNotifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است/نیست')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاع رسانی',
                'verbose_name_plural': 'اطلاع رسانی ها',
            },
        ),
    ]
