# Generated by Django 5.0.7 on 2024-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads', verbose_name='تصویر')),
                ('link', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(verbose_name='فعال باشد/نباشد')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگوی سایت')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس با ما')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل تماس با ما')),
                ('location', models.CharField(max_length=200, verbose_name='مکان')),
                ('about_us', models.TextField(verbose_name='متن درباره ما')),
                ('is_active', models.BooleanField(verbose_name='فعال باشد/نباشد')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='SliderSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders', verbose_name='تصویر اسلایدر')),
                ('link', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(verbose_name='فعال باشد/نباشد')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
