# Generated by Django 5.0.7 on 2024-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskandAnwserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('anwser', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'پرسش و پاسخ ها',
            },
        ),
    ]
