# Generated by Django 5.0.7 on 2024-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings_module', '0002_askandanwsermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='askandanwsermodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال باشد/نباشد'),
        ),
    ]
