# Generated by Django 5.0.7 on 2024-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings_module', '0003_askandanwsermodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخته شدن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد/نباشد')),
                ('text', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
            },
        ),
    ]
