# Generated by Django 5.0.7 on 2024-07-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان(خبر/مقاله)')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد/نباشد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس در مرورگر')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles', verbose_name='تصویر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('des', models.TextField(verbose_name='توضیحات')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='زمان ساخته شدن')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس در مرورگر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategorymodel', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(to='article_module.articletagmodel', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
            },
        ),
    ]
