# Generated by Django 5.0.7 on 2024-07-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_articlemodel_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='زمان ساخته شدن')),
                ('text', models.TextField(verbose_name='محتوای نظر')),
                ('is_publish', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('comment_like', models.IntegerField(default=0, verbose_name='تعداد لایک های کامنت')),
                ('comment_dislike', models.IntegerField(default=0, verbose_name='تعداد دیس لایک های کامنت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.articlemodel', verbose_name='وبلاگ')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecommentmodel', verbose_name='والد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
