# Generated by Django 5.0.7 on 2024-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_articlecommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentmodel',
            name='comment_like',
            field=models.CharField(default=0, max_length=100, verbose_name='تعداد لایک های کامنت'),
        ),
    ]
