# Generated by Django 5.0.7 on 2024-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_articlecommentmodel_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentmodel',
            name='comment_like',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک های کامنت'),
        ),
    ]
